export  const apiSources = {
  "ABC News": "abc-news-au",
  "Al Jazeera": "al-jazeera-english",
  "Ars Technica": "ars-technica",
  "Associated Press": "associated-press",
  "BBC News": "bbc-news",
  "BBC Sports": "bbc-sport",
  "Bild": "bild",
  "Bloomberg": "bloomberg",
  "Breitbart": "breitbart-news",
  "Buisness Insider": "business-insider",
  "Buisness Insider Uk": "business-insider-uk",
  "Buzzfeed": "buzzfeed",
  "Cnbc": "cnbc",
  "CNN": "cnn",
  "Daily Mail": "daily-mail",
  "Engadget": "engadget",
  "Entertainment Weekly": "entertainment-weekly",
  "Espn": "espn",
  "Focus": "focus",
  "Fortune": "fortune",
  "Fox Sports": "fox-sports",
  "Google News": "google-news",
  "Hacker News": "hacker-news",
  "Ign": "ign",
  "Independent": "independent",
  "Mashable": "mashable",
  "Metro": "metro",
  "Mirror": "mirror",
  "Mtv News": "mtv-news",
  "National Geographic": "national-geographic",
  "News Scientist": "new-scientist",
  "Newsweek": "newsweek",
  "New York Magazine": "new-york-magazine",
  "Polygon": "polygon",
  "Recode": "recode",
  "Reddit R/All": "reddit-r-all",
  "Reuters": "reuters",
  "Techcrunch": "techcrunch",
  "Techradar": "techradar",
  "The Economist": "the-economist",
  "The Hindu": "the-hindu",
  "The Huffington Post": "the-huffington-post",
  "The New York Times": "the-new-york-times",
  "The Next Web": "the-next-web",
  "The Telegraph": "the-telegraph",
  "The Verger": "the-verge",
  "The Wall Street Journal": "the-wall-street-journal",
  "The Washington Post": "the-washington-post",
  "Time": "time",
  "Usa Today": "usa-today"
}